"""empty message

Revision ID: 473b8a3d002d
Revises: 1fc2bc0c07c1
Create Date: 2021-12-16 19:34:56.659292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473b8a3d002d'
down_revision = '1fc2bc0c07c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_data', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_data', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('modify_data')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('modify_data')

    # ### end Alembic commands ###
